package com.cccclab.cadtool.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CheckBox;
import com.vaadin.ui.Table;
import com.vaadin.ui.Upload;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { ¡K }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CADTWebPageDesign extends VerticalLayout {
	protected com.vaadin.ui.CheckBox chk_ncld;
	protected com.vaadin.ui.CheckBox chk_nclx;
	protected com.vaadin.ui.CheckBox chk_roc;
	protected com.vaadin.ui.Button btn_send;
	protected com.vaadin.ui.Button btn_download;
	protected com.vaadin.ui.Upload upload_select;
	protected com.vaadin.ui.Table tb_files;

	public CADTWebPageDesign() {
		Design.read(this);
	}
}
