package com.cccclab.cadtool.design;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;
import org.vaadin.aceeditor.AceEditor;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { ¡K }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class CADTFileEditorDesign extends VerticalLayout {
	protected Button btn_save;
	protected Button btn_cancle;
	protected AceEditor editor_code;

	public CADTFileEditorDesign() {
		Design.read(this);
	}
}
